preset: laravel

enabled:
  - alpha_ordered_imports
  - concat_with_spaces

disabled:
  - unused_use
  - trailing_comma_in_multiline_array
  - concat_without_spaces

finder:
  not-name:
    - index.php
    - server.php
  exclude:
    - "tests"
  name:
    - "*.php"