preset: laravel

enabled:
  - alpha_ordered_imports

disabled:
  - length_ordered_imports
  - unused_use
  - trailing_comma_in_multiline_array

finder:
  not-name:
    - index.php
    - server.php
  exclude:
    - "tests"
  name:
    - "*.php"